openapi: 3.0.0
info:
  title: Sensor API
  version: 1.0.0
  description: API for managing environmental sensor detections, sensor locations, and forwarding alerts.

servers:
  - url: http://localhost:3000/v0
    description: Local development server

paths:
  /sensor/{sensorType}/{sensorId}/detections:
    get:
      summary: Retrieve detections from a sensor
      parameters:
        - in: path
          name: sensorType
          required: true
          schema:
            type: string
        - in: path
          name: sensorId
          required: true
          schema:
            type: string
        - in: query
          name: from
          description: Start timestamp in milliseconds (inclusive)
          schema:
            type: integer
        - in: query
          name: to
          description: End timestamp in milliseconds (inclusive)
          schema:
            type: integer
        - in: query
          name: last
          description: Return the last N detections
          schema:
            type: integer
      responses:
        '200':
          description: List of sensor detections
          content:
            application/json:
              example:
                - sensorId: "sensor-2"
                  sensorName: "Temp Sensor 2"
                  value: 22.5
                  unit: "°C"
                  timestamp: 1682179200000
                  latitude: 43.06
                  longitude: 141.35
        '400':
          description: Invalid sensor type or query parameters
          content:
            application/json:
              example:
                error: "Unsupported sensor type: invalidType"
        '404':
          description: Sensor ID not found
          content:
            application/json:
              example:
                error: "The input sensor ID does not exist."

    post:
      summary: Save a detection
      parameters:
        - in: path
          name: sensorType
          required: true
          schema:
            type: string
        - in: path
          name: sensorId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            example:
              sensorName: "Temp Sensor 1"
              value: 23.4
              unit: "°C"
              timestamp: 1682181000000
              latitude: 43.066
              longitude: 141.345
      responses:
        '201':
          description: Detection successfully saved
          content:
            application/json:
              example:
                success: "Detection saved successfully."
        '400':
          description: Validation or data error
          content:
            application/json:
              examples:
                missingBody:
                  summary: No request body
                  value:
                    error: "Missing detection data in the request body"
                missingValue:
                  summary: Missing value field
                  value:
                    error: "Missing required field: value"

  /sensor/{sensorType}/locations:
    get:
      summary: Get all sensor locations of a given type
      parameters:
        - in: path
          name: sensorType
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of sensor locations
          content:
            application/json:
              example:
                - sensorId: "sensor-1"
                  latitude: 43.0621
                  longitude: 141.3544
                - sensorId: "sensor-2"
                  latitude: 43.0667
                  longitude: 141.35
        '404':
          description: No locations found for the specified sensor type
          content:
            application/json:
              example:
                error: 'No locations found for sensor type "temp".'

  /alerts:
    post:
      summary: Forward an alert
      requestBody:
        required: true
        content:
          application/json:
            example:
              sensorId: "sensor-3"
              alertType: "threshold_exceeded"
              message: "Temperature exceeded safety threshold."
              timestamp: 1682181300000
      responses:
        '200':
          description: Alert forwarded successfully
          content:
            application/json:
              example:
                success: "Alert forwarded successfully."
