import { STATUS_PATH } from "../../../../routes/v0/paths/health.paths";
import { AUTHORIZED_PATH, DELETE_ADMIN_PATH, DELETE_PATH, LOGIN_ADMIN_PATH, LOGIN_PATH, REGISTER_ADMIN_PATH, REGISTER_PATH } from "../../../../routes/v0/paths/user.paths";

const BASE_USER_ROUTE_V0 = "/v0/user"
const BASE_HEALTH_ROUTE_V0 = "/v0/health";

const DELETE_USER_ROUTE = BASE_USER_ROUTE_V0 + DELETE_PATH;
const DELETE_ADMIN_ROUTE = BASE_USER_ROUTE_V0 + DELETE_ADMIN_PATH;
const REGISTER_USER_ROUTE = BASE_USER_ROUTE_V0 + REGISTER_PATH;
const REGISTER_ADMIN_ROUTE = BASE_USER_ROUTE_V0 + REGISTER_ADMIN_PATH;
const LOGIN_USER_ROUTE = BASE_USER_ROUTE_V0 + LOGIN_PATH;
const LOGIN_ADMIN_ROUTE = BASE_USER_ROUTE_V0 + LOGIN_ADMIN_PATH;
const JWT_AUTHORIZED_ROUTE = BASE_USER_ROUTE_V0 + AUTHORIZED_PATH;
const HEALTH_API_ROUTE = BASE_HEALTH_ROUTE_V0 + STATUS_PATH;


export { DELETE_ADMIN_ROUTE, DELETE_USER_ROUTE,
     REGISTER_ADMIN_ROUTE, REGISTER_USER_ROUTE,
      LOGIN_ADMIN_ROUTE, LOGIN_USER_ROUTE,
       JWT_AUTHORIZED_ROUTE, HEALTH_API_ROUTE }