openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
  description: API documentation for user registration, login, token verification, and deletion.
servers:
  - url: http://localhost:7777
    description: Local development server
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                X-User-Email:
                  type: string
                  description: User's email address
                X-User-Password:
                  type: string
                  description: User's password
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  X-User-Email:
                    type: string
                    description: Admin's email address
                  X-User-Token:
                    type: string
                    description: U  ser's JWT token
                  X-User-Token-Expiration:
                    type: number
                    description: User's JWT token expiration date
        400:
          description: Bad request

  /admin/register:
    post:
      summary: Register a new admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                X-User-Email:
                  type: string
                  description: Admin's email address
                X-User-Password:
                  type: string
                  description: Admin's password
                X-Api-Key:
                  type: string
                  description: Admin API key
      responses:
        201:
          description: Admin registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  X-User-Email:
                    type: string
                    description: Admin's email address
                  X-User-Token:
                    type: string
                    description: U  ser's JWT token
                  X-User-Token-Expiration:
                    type: number
                    description: User's JWT token expiration date
        401:
          description: Unauthorized

  /login:
    post:
      summary: Login as a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                X-User-Email:
                  type: string
                  description: User's email address
                X-User-Password:
                  type: string
                  description: User's password
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  X-User-Email:
                    type: string
                    description: Admin's email address
                  X-User-Token:
                    type: string
                    description: U  ser's JWT token
                  X-User-Token-Expiration:
                    type: number
                    description: User's JWT token expiration date
        400:
          description: Bad request
  /admin/login:
    post:
      summary: Login as an admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                X-User-Email:
                  type: string
                  description: Admin's email address
                X-User-Password:
                  type: string
                  description: Admin's password
                X-Api-Key:
                  type: string
                  description: Admin API key
      responses:

        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  X-User-Email:
                    type: string
                    description: Admin's email address
                  X-User-Token:
                    type: string
                    description: U  ser's JWT token
                  X-User-Token-Expiration:
                    type: number
                    description: User's JWT token expiration date
        401:
          description: Unauthorized

  /authorized:
    post:
      summary: Verify JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                X-User-Token:
                  type: string
                  description: JWT token
      responses:
        202:
          description: Token verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  X-User-Token-Expiration:
                    type: number
                    description: User's JWT token expiration date
        401:
          description: Unauthorized
        400:
          description: Bad request

  /delete:
    delete:
      summary: Delete a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                X-User-Email:
                  type: string
                  description: User's email address
      responses:
        200:
          description: User deleted successfully
        400:
          description: Bad request

  /admin/delete:
    delete:
      summary: Delete an admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                X-User-Email:
                  type: string
                  description: Admin's email address
                X-Api-Key:
                  type: string
                  description: Admin API key
      responses:
        200:
          description: Admin deleted successfully
        401:
          description: Unauthorized
        400:
          description: Bad request
