services:
  sensor-registry:
    image: matteoiorio/sensor-registry:0.0.7
    ports:
      - target: 7777
        published: 7777
    depends_on:
      - sensor-database
    networks:
      - app-network
  sensor-database:
    image: mongo
    ports:
      - target: 27017
        published: 27019
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app-network
networks:
  app-network:
    driver: bridge