const USER_EMAIL_HEADER = "X-User-Email";
const USER_JWT_TOKEN_HEADER = "X-User-Token";
const USER_JWT_TOKEN_EXPIRATION_HEADER = "X-User-Token-Expiration";

export { USER_EMAIL_HEADER, USER_JWT_TOKEN_HEADER, USER_JWT_TOKEN_EXPIRATION_HEADER }