const USER_EMAIL_BODY = 'userEmail';
const USER_JWT_TOKEN_BODY = 'userToken';
const USER_PASSWORD_BODY = 'userPassword';
const USER_JWT_TOKEN_EXPIRATION_BODY = 'userTokenExpiration';
const USER_ACTION_BODY = 'action';

export { USER_EMAIL_BODY, USER_JWT_TOKEN_BODY, USER_PASSWORD_BODY, USER_JWT_TOKEN_EXPIRATION_BODY, USER_ACTION_BODY };
