const BASE_SENSOR_PATH_V0 = '/v0/sensor';

const REGISTER_PATH = '/register';
const REGISTER_ROUTE = BASE_SENSOR_PATH_V0 + REGISTER_PATH;

const ALL_PATH = '/all';
const ALL_ROUTE = BASE_SENSOR_PATH_V0 + ALL_PATH;

const SHUT_OFF_PATH = '/shutoff';
const SHUT_OFF_ROUTE = BASE_SENSOR_PATH_V0 + SHUT_OFF_PATH;

const QUERIES_PATH = '/queries';

export {
    BASE_SENSOR_PATH_V0,
    REGISTER_PATH,
    ALL_PATH,
    SHUT_OFF_PATH,
    REGISTER_ROUTE,
    ALL_ROUTE,
    SHUT_OFF_ROUTE,
    QUERIES_PATH,
};
