const BASE_SENSOR_PATH_V0 = '/v0/sensor';

const REGISTER_PATH = '/register';
const REGISTER_ROUTE = BASE_SENSOR_PATH_V0 + REGISTER_PATH;

const ALL_PATH = '/all';
const ALL_ROUTE = BASE_SENSOR_PATH_V0 + ALL_PATH;

const ALL_INFO_PATH = '/infos';
const ALL_INFO_ROUTE = BASE_SENSOR_PATH_V0 + ALL_INFO_PATH;

const TYPE_PATH = '/type';
const TYPE_ROUTE = BASE_SENSOR_PATH_V0 + TYPE_PATH;

const SHUT_DOWN_PATH = '/shutdown';
const SHUT_DOWN_ROUTE = BASE_SENSOR_PATH_V0 + SHUT_DOWN_PATH;

const UPDATE_SENSOR_PATH = '/update';
const UPDATE_SENSOR_ROUTE = BASE_SENSOR_PATH_V0 + UPDATE_SENSOR_PATH;

export {
    BASE_SENSOR_PATH_V0,
    REGISTER_PATH,
    ALL_PATH,
    SHUT_DOWN_PATH,
    REGISTER_ROUTE,
    ALL_ROUTE,
    SHUT_DOWN_ROUTE,
    ALL_INFO_PATH,
    ALL_INFO_ROUTE,
    TYPE_PATH,
    TYPE_ROUTE,
    UPDATE_SENSOR_PATH,
    UPDATE_SENSOR_ROUTE,
};
