const BASE_PATH_V0 = '/v0/api';

const ANY_PARAMETER = '/*';
const AUTHENTICATION_SERVICE = '/authentication';
const AUTHENTICATION_PATHS = AUTHENTICATION_SERVICE + ANY_PARAMETER;
const AUTHENTICATION_COMPLETE_ROUTE = BASE_PATH_V0 + AUTHENTICATION_PATHS;

const NOTIFICATION_SERVICE_HOSTNAME = 'notification-service';
const NOTIFICATION_SERVICE_PORT = '4444';
const NOTIFICATION_SERVICE_ENDPOINT = `http://${NOTIFICATION_SERVICE_HOSTNAME}:${NOTIFICATION_SERVICE_PORT}`;
const NOTIFICATION_SERVICE = '/alert';
const NOTIFICATION_TOPICS_PATH = NOTIFICATION_SERVICE + '/topics';
const NOTIFICATION_TOPIC_QUERIES_PATH = NOTIFICATION_TOPICS_PATH + '/queries';
const NOTIFICATION_SUBSCRIPTION_PATH = NOTIFICATION_TOPICS_PATH + 'subscribe';

export {
    BASE_PATH_V0,
    AUTHENTICATION_SERVICE,
    AUTHENTICATION_PATHS,
    AUTHENTICATION_COMPLETE_ROUTE,
    NOTIFICATION_SERVICE_ENDPOINT,
    NOTIFICATION_TOPICS_PATH,
    NOTIFICATION_TOPIC_QUERIES_PATH,
    NOTIFICATION_SUBSCRIPTION_PATH,
};
