const BASE_PATH_V0 = "/v0/api"

const AUTHENTICATION_PATHS = "/authentication/*"
const AUTHENTICATION_ROUTES = BASE_PATH_V0 + AUTHENTICATION_PATHS;

export { BASE_PATH_V0, AUTHENTICATION_PATHS, AUTHENTICATION_ROUTES }