const BASE_PATH_V0 = '/v0/api';

const ANY_PARAMETER = '/*';
const AUTHENTICATION_SERVICE = '/authentication';
const AUTHENTICATION_PATHS = AUTHENTICATION_SERVICE + ANY_PARAMETER;
const AUTHENTICATION_COMPLETE_ROUTE = BASE_PATH_V0 + AUTHENTICATION_PATHS;

export { BASE_PATH_V0, AUTHENTICATION_SERVICE, AUTHENTICATION_PATHS, AUTHENTICATION_COMPLETE_ROUTE };
