name: Repo QA and Semantic Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ['notification-service', 'sensor-registry', 'authentication-service', 'detection-service' ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23.10.0'

      - name: Install deps
        run: npm install
        working-directory: ${{ matrix.project }}

      - name: Run linter
        run: npm run lint
        working-directory: ${{ matrix.project }}

      - name: Run tests with coverage
        run: npm test -- --coverage
        working-directory: ${{ matrix.project }}
        continue-on-error: false # extra carefulness that if test does not passes fail instant

      - name: Publish CodeCov report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23.10.0'

      - name: install deps
        run: npm i

      - name: run semantic-release
        run: npm i && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
