name: Deploy on Google Cloud Platform

on:
  workflow_run:
    workflows:
      - Check repo integrity
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ['notification-service', 'sensor-registry', 'authentication-service', 'detection-service' ]
      fail-fast: false
    
    steps:
      - name: Clone Cloud utility
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'MatteoIorio11'
          repository: 'service-builder'
          branch: 'main'
   
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./service-builder/.python-version"

      - name: Set up UV
        uses: astral-sh/setup-uv@v5

      - name: Install the Python project using UV
        run: |
          cd service-builder
          uv sync 
  
      - name: Authenticate Google Cloud user
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_TOKEN }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3S

      - name: Login to Google Cloud Artifact
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
          username: _json_key
          password: '${{ secrets.GCP_TOKEN }}'

