name: Deploy on Google Cloud Platform

on:
  workflow_run:
    workflows:
      - Check repo integrity
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ['notification-service', 'sensor-registry', 'authentication-service', 'detection-service' ]
      fail-fast: false
    
    steps:
      - name: Clone Cloud utility
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'MatteoIorio11'
          repository: 'service-builder'
          branch: 'main'

      - name: Set up UV
        uses: astral-sh/setup-uv@v5
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./service-builder/.python-version"


  