name: Release project on NPM

on:
  push:
    branches: [main]
    paths:
      - 'notification-service/**'
      - 'detection-service/**'
      - 'authentication-service/**'
      - 'sensor-registry/**'
      - 'api-gateway/**'
      - '.github/workflows/npm-sem-release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - notification-service
          - detection-service
          - authentication-service
          - sensor-registry
          - api-gateway

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23.10.0'
    
      - name: install deps
        run: npm i

      - name: run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
